### ISSUE TITLE
Compile BLE Speaker mode failed

### ISSUE THREAD

**Issue by vibnwis** [kodera2t/ESP32_OLED_webradio#11]
When set to Bluetooth Speaker mode. It failed the compilation.

make[1]: *** No rule to make target '/Users/kodera2t/esp/esp-idf/components/bt/bluedroid/bta/dm/bta_dm_api.c', needed by 'bluedroid/bta/dm/bta_dm_api.o'.  Stop.
/home/esp32/esp/esp-idf/make/project.mk:450: recipe for target 'component-bt-build' failed
make: *** [component-bt-build] Error 2

**Comment by elgato45** [comment]
Same error !!!

make[1]: *** No rule to make target `/Users/kodera2t/esp/esp-idf/components/bt/bluedroid/bta/dm/bta_dm_act.c', needed by `bluedroid/bta/dm/bta_dm_act.o'.  Stop.
make: *** [component-bt-build] Error 2

**Comment by vibnwis** [comment]
It looks like the owner has removed the component folder from the repo. Hence, the compilation could not find '..../bta_dm_act.c'.  I suggest to move on to other repos. As suggested by the owner, he will not provide any supports as he merely clone from others. The owner is only interested in selling his hardware. This repo is being used to realise the goal.
