### ISSUE TITLE
New product 2

### ISSUE THREAD

**Issue by vibnwis** [kodera2t/ESP32_OLED_webradio#15]
Found a product that is great for ESP32 development and final product as well. Check this out, https://hackaday.io/project/26267-m5stack. It is always available in Aliexpress and Banggood. It has built-in Audio amplifier, LCD TFT, plenty of GPIOs- almost all available for user's access, battery included and last but not least, 3 buttons. IMO, this is the most suitable board for all ESP32 applications and prototyping. Most importantly, it has got all the drivers and supports you can get from GitHub and a company to contact for support.

**Comment by kodera2t** [comment]
This is not issue.
