### ISSUE TITLE
static IP + DNS

### ISSUE THREAD

**Issue by zajaklis** [kodera2t/ESP32_OLED_webradio#3]
thanks for great work with webradio.
To speed up startup time i tried to set static ip + dns.
with static there were no problems but i failed in DNS.

#define DEVICE_DNS          "8.8.8.8"
ip_addr_t dnsserver;
inet_pton(AF_INET, DEVICE_DNS, &dnsserver);
dns_setserver(0, &dnsserver);

esp32 reboots because of DNS resolution fail

**Comment by kodera2t** [comment]
Hello, indeed it is "beyond problem" to web radio system. I have not tried static IP but you may find the solution in ESP32 forum. thank you!
