### ISSUE TITLE
In BT mode, it reboot repeatedly  in terms of 5~6 second with latest esp-idf

### ISSUE THREAD

**Issue by carhero** [kodera2t/ESP32_OLED_webradio#5]
I'm using ESP32 ADB type_R EVB
Webradio is quite good but in BT mode, it reboot repeatedly in terms of 5~6 second.

I just followed your blog posted below link
https://hackaday.io/project/21321-esp32-monster-board/log/59598-how-to-start-bluetooth-i2s-audio

I tried to enlarge BT task stack size in menuconfig but it did not fix.
![asdf](https://user-images.githubusercontent.com/807556/28152513-e6cfce1c-67db-11e7-96df-b916ae1b93ab.jpg)

Could you reproduce this issue in your side?
If so, please review this!!

If i try to connect source device and playing music quickly then BT sound is he
ard until auto reboot.

Please refer to BT log.
[OLED_BT_Crash_log.txt](https://github.com/kodera2t/ESP32_OLED_webradio/files/1144202/OLED_BT_Crash_log.txt)

**Comment by carhero** [comment]
Dear Mr kodera2t

I have tested ESP32_OLED_webradio( BT mode) in windows and linux(V/M, ubuntu17.04)
The result is same.  Rebooting repeatedly in 5~6 second.
Could you share your ESP-IDF code which work correctly?
I want to review why it does not work correctly in latest ESP-IDF.

Regard
Y.H.Cha

**Comment by kodera2t** [comment]
Hello Mr. Cha!
Recently I've not followed up-to-date esp-idf but just now I've confirmed the issue. At this moment I don't have quick remedy for it but also please check the great original web radio source, which has more evolution than my folk. The original one is
https://github.com/MrBuddyCasino/ESP32_MP3_Decoder
Also I've not checked by this original with updated esp-idf combination but it might already solved the issue.

**Comment by carhero** [comment]
I fixed this bug.
Solution is very simple.

In the app_main.c file 

void app_main()
{
    print_mux = xSemaphoreCreateMutex();
    ESP_LOGI(TAG, "starting app_main()");
    ESP_LOGI(TAG, "RAM left: %u", esp_get_free_heap_size());

    init_hardware();

#ifdef CONFIG_BT_SPEAKER_MODE
    bt_speaker_start(create_renderer_config());
#else
    start_wifi();
    start_web_radio();
#endif
    i2c_example_master_init();
    SSD1306_Init();
    i2c_test();
    ESP_LOGI(TAG, "RAM left %d", esp_get_free_heap_size());
    // ESP_LOGI(TAG, "app_main stack: %d\n", uxTaskGetStackHighWaterMark(NULL));

#ifdef CONFIG_BT_SPEAKER_MODE   **// Y.H.Cha : Add this to run in Web radio mode only**
    xTaskCreate(&http_server, "http_server", 2048, NULL, 5, NULL);
#endif    
}

You may update this to fix it.

**Comment by kodera2t** [comment]
Thank you!!! I will add your fix right now!

**Comment by carhero** [comment]
There is missing 'n' in the #ifdef

Please replace 
#ifdef CONFIG_BT_SPEAKER_MODE
to
#if**n**def CONFIG_BT_SPEAKER_MODE
