### ISSUE TITLE
factory size

### ISSUE THREAD

**Issue by karawin** [kodera2t/ESP32_OLED_webradio#6]
I changed the size of the factory to 2M because the default one was too small with the new idf.
# Name,   Type, SubType, Offset,  Size, Flags
# Note: if you change the phy_init or app partition offset, make sure to change the offset in Kconfig.projbuild
nvs,      data, nvs,     0x9000,  0x6000,
phy_init, data, phy,     0xf000,  0x1000,
factory,  app,  factory, 0x10000, 2M,

in partitions.csv custom partition.

**Comment by kodera2t** [comment]
Sorry for very long my absence and ignorance. Thank you for pointing out the issue for current esp-idf. Now it's fixed. Thank you!
