### ISSUE TITLE
new product

### ISSUE THREAD

**Issue by chegewara** [kodera2t/ESP32_OLED_webradio#8]
Just found it:
https://github.com/LilyGO/TTGO-TM-ESP32

https://pl.aliexpress.com/item/Tm-ESP32-Muzyka-PCM5102A-albumy-TFT-2-4-cal-Modu-WiFi-Bluetooth-SD-Card/32848388341.html?spm=a2g17.10010108.1000014.6.51ab11beXXJqEq&traffic_analysisId=recommend_3035_null_null_null&scm=1007.13338.80878.000000000000000&pvid=5e1ede8b-0b31-4815-8ca2-21d4041f529c&tpp=1

**Comment by pilnikov** [comment]
https://yadi.sk/i/EuIp8alo3S4d3s
shematic diagram on this
display controller  ST7789V

**Comment by vibnwis** [comment]
http://www.m5stack.com/ looks very promising development board plus your own product(device). A wide range of drivers and a huge number of members to discuss with. More important, the manufacturer is providing completely free support.

**Comment by kodera2t** [comment]
This is not issue.

**Comment by vibnwis** [comment]
Indeed. However, since this is an open source forum where encourages sharing and peer-support. It is helpful for interested users to have options of hardware that could use the open source software, WebRadio, is it not?

**Comment by chegewara** [comment]
Im sorry @kodera2t for that. I just wanted to show you that someone is using your code to sell product and i did not expect this issue will become advertising issue.

No, i dont agree, this is not even a forum and for sure not a place to post advertising links. You should do this here esp32.com

**Comment by vibnwis** [comment]
My apologies if anyone felt that way.  Like you, I am just a user which I found out that it is useful for this code or a good alternative. Also, I think it is a good idea to share. BTW, the product is also available in Hackaday.io and they shared their code on GitHub too. Check this out, https://github.com/m5stack/M5Stack.  So, at the end, it is about sharing. In addition, Kodera2t is not even the owner of the code, MrBuddy is. Even MrBuddy added the link of Kodera2t who actually capitalizes on the open source resources. Does Kodera2t using open source code to sell his products?  Don't get me wrong, I don't think it is wrong if  he does. Has anyone advertised for commercial purposes? Like Linux forums. members list all hardware (commercial or non-commercial) for users to choose from. Something is very wrong here if someone thinks that this particular piece of open source item can only use on one hardware and do not allow people to share information of alternative solutions.

**Comment by vibnwis** [comment]
FYI, Kodera2t is using MrBuddy's code to sell his(Kodera2t) products. Again, I don't think it is wrong. Not the other way round. I think it is time to revisit the code of ethics here in GitHub before passing unnecessary judgement.
