### ISSUE TITLE
/mdns_task.c:29:5: error: unknown type name 'mdns_server_t'

### ISSUE THREAD

**Issue by vibnwis** [kodera2t/ESP32_OLED_webradio#9]
Experiencing the error and used the command grep -rnw '.' -e 'mdns_server_t' to find the definition but not found. Very strange! Any advice? please

**Comment by vibnwis** [comment]
I had issued a question to MrBuddyCasino/ESP32_MP3_Decode, and he responded that the related file had been removed resulting in the mdsn_server_t not found. Apparently, you still use mdns_server_t.  I presume if you do a fresh pull request from MrBuddyCasino/ESP32_MP3_Decode, you will have the same encounter. However, I am trying to give some background of the issues. Hopefully, you can sort it out soon.

**Comment by vibnwis** [comment]
I have resolved the issue by removing mdns_task folder in components folder and commented out the mdns_task.h from app_main.c. The mdns_task folder has been removed from  MrBuddyCasino/ESP32_MP3_Decode. However, it still remains in the repositories of the subsequent forks owners.

I am still puzzling how they manage to compile without errors?

**Comment by kodera2t** [comment]
hello, now it's fixed as same as your way. Indeed, this function was not used... ;-)
